---
- name: Common setup for all nodes
  hosts: all
  become: true
  roles:
    - role: common

- name: Setup K3s Control Plane Node
  hosts: controlplane
  become: true
  roles:
    - role: k3s_control_plane

- name: Setup K3s Worker Node
  hosts: worker
  become: true
  vars:
    k3s_token: "{{ hostvars['control-node']['token'] }}"
  roles:
    - role: k3s_agent
